export type TFQuestion = {
  id: string;
  category: string;
  statement: string;
  isTrue: boolean;
};

export const TF_QUESTION_POOL: TFQuestion[] = [
  // --- SCIENCE (1-15) ---
  { id: "tf1", category: "SCIENCE", statement: "Light travels faster than sound.", isTrue: true },
  { id: "tf2", category: "SCIENCE", statement: "The Great Wall of China is visible from space with the naked eye.", isTrue: false },
  { id: "tf3", category: "SCIENCE", statement: "Water boils at a lower temperature at higher altitudes.", isTrue: true },
  { id: "tf4", category: "SCIENCE", statement: "Electrons are larger than protons.", isTrue: false },
  { id: "tf5", category: "SCIENCE", statement: "Sound waves can travel through a vacuum.", isTrue: false },
  { id: "tf6", category: "SCIENCE", statement: "Venus is the hottest planet in our solar system.", isTrue: true },
  { id: "tf7", category: "SCIENCE", statement: "Humans share approximately 98% of their DNA with chimpanzees.", isTrue: true },
  { id: "tf8", category: "SCIENCE", statement: "Penicillin was discovered by Alexander Fleming.", isTrue: true },
  { id: "tf9", category: "SCIENCE", statement: "Sharks are mammals.", isTrue: false },
  { id: "tf10", category: "SCIENCE", statement: "Diamond is made entirely of carbon atoms.", isTrue: true },
  { id: "tf11", category: "SCIENCE", statement: "Absolute zero is 0 degrees Celsius.", isTrue: false },
  { id: "tf12", category: "SCIENCE", statement: "Lightning is hotter than the surface of the Sun.", isTrue: true },
  { id: "tf13", category: "SCIENCE", statement: "The human heart has five chambers.", isTrue: false },
  { id: "tf14", category: "SCIENCE", statement: "Helium is the lightest element in the periodic table.", isTrue: false },
  { id: "tf15", category: "SCIENCE", statement: "Dolphins sleep with one eye open.", isTrue: true },

  // --- GEOGRAPHY (16-30) ---
  { id: "tf16", category: "GEOGRAPHY", statement: "Australia is both a country and a continent.", isTrue: true },
  { id: "tf17", category: "GEOGRAPHY", statement: "The Nile River flows into the Indian Ocean.", isTrue: false },
  { id: "tf18", category: "GEOGRAPHY", statement: "Monaco is the smallest sovereign country in the world.", isTrue: false },
  { id: "tf19", category: "GEOGRAPHY", statement: "Mount Kilimanjaro is located in Tanzania.", isTrue: true },
  { id: "tf20", category: "GEOGRAPHY", statement: "Alaska has the longest coastline of any US state.", isTrue: true },
  { id: "tf21", category: "GEOGRAPHY", statement: "The Amazon Rainforest produces over 50% of the world's oxygen.", isTrue: false },
  { id: "tf22", category: "GEOGRAPHY", statement: "Cairo is the capital of Egypt.", isTrue: true },
  { id: "tf23", category: "GEOGRAPHY", statement: "The Pacific Ocean is larger than all Earth's landmasses combined.", isTrue: true },
  { id: "tf24", category: "GEOGRAPHY", statement: "Iceland has no active volcanoes.", isTrue: false },
  { id: "tf25", category: "GEOGRAPHY", statement: "Madrid is the capital of Spain.", isTrue: true },
  { id: "tf26", category: "GEOGRAPHY", statement: "The Equator passes through Europe.", isTrue: false },
  { id: "tf27", category: "GEOGRAPHY", statement: "Lake Baikal is the deepest lake on Earth.", isTrue: true },
  { id: "tf28", category: "GEOGRAPHY", statement: "Brazil is the only country in the Americas that speaks Portuguese.", isTrue: true },
  { id: "tf29", category: "GEOGRAPHY", statement: "The Dead Sea is below global sea level.", isTrue: true },
  { id: "tf30", category: "GEOGRAPHY", statement: "Tokyo was originally named Edo.", isTrue: true },

  // --- HISTORY (31-45) ---
  { id: "tf31", category: "HISTORY", statement: "The Roman Empire fell in the 15th century.", isTrue: false },
  { id: "tf32", category: "HISTORY", statement: "World War I started in 1914.", isTrue: true },
  { id: "tf33", category: "HISTORY", statement: "Napoleon Bonaparte was born on the island of Corsica.", isTrue: true },
  { id: "tf34", category: "HISTORY", statement: "Cleopatra was ethnically Egyptian.", isTrue: false },
  { id: "tf35", category: "HISTORY", statement: "The Liberty Bell was made in Philadelphia.", isTrue: false },
  { id: "tf36", category: "HISTORY", statement: "The Titanic sank on its maiden voyage.", isTrue: true },
  { id: "tf37", category: "HISTORY", statement: "Genghis Khan founded the Mongol Empire.", isTrue: true },
  { id: "tf38", category: "HISTORY", statement: "The Magna Carta was signed in 1215.", isTrue: true },
  { id: "tf39", category: "HISTORY", statement: "The Aztec civilization was centered in modern-day Peru.", isTrue: false },
  { id: "tf40", category: "HISTORY", statement: "Neil Armstrong was the first person to walk on the Moon.", isTrue: true },
  { id: "tf41", category: "HISTORY", statement: "The French Revolution began in 1789.", isTrue: true },
  { id: "tf42", category: "HISTORY", statement: "The United States purchased Alaska from Russia.", isTrue: true },
  { id: "tf43", category: "HISTORY", statement: "Julius Caesar was the first Emperor of Rome.", isTrue: false },
  { id: "tf44", category: "HISTORY", statement: "The Berlin Wall fell in 1989.", isTrue: true },
  { id: "tf45", category: "HISTORY", statement: "Christopher Columbus reached North America in 1492.", isTrue: false },

  // --- POP CULTURE (46-60) ---
  { id: "tf46", category: "POP CULTURE", statement: "The Beatles had four core members.", isTrue: true },
  { id: "tf47", category: "POP CULTURE", statement: "Mickey Mouse originally wore red gloves.", isTrue: false },
  { id: "tf48", category: "POP CULTURE", statement: "Michael Jackson released the album 'Thriller'.", isTrue: true },
  { id: "tf49", category: "POP CULTURE", statement: "Batman's butler is named Jarvis.", isTrue: false },
  { id: "tf50", category: "POP CULTURE", statement: "The Simpsons first aired as a full series in 1989.", isTrue: true },
  { id: "tf51", category: "POP CULTURE", statement: "Katy Perry performed at the Super Bowl XLIX Halftime Show.", isTrue: true },
  { id: "tf52", category: "POP CULTURE", statement: "Spider-Man was created by Stan Lee and Steve Ditko.", isTrue: true },
  { id: "tf53", category: "POP CULTURE", statement: "The character Mario was originally named Jumpman.", isTrue: true },
  { id: "tf54", category: "POP CULTURE", statement: "Barbie's full name is Barbara Millicent Roberts.", isTrue: true },
  { id: "tf55", category: "POP CULTURE", statement: "Avatar is directed by Steven Spielberg.", isTrue: false },
  { id: "tf56", category: "POP CULTURE", statement: "Spotify was founded in Sweden.", isTrue: true },
  { id: "tf57", category: "POP CULTURE", statement: "Godzilla originated in Japanese cinema in 1954.", isTrue: true },
  { id: "tf58", category: "POP CULTURE", statement: "The Hunger Games trilogy was written by Veronica Roth.", isTrue: false },
  { id: "tf59", category: "POP CULTURE", statement: "Pac-Man was originally called Puck-Man in Japan.", isTrue: true },
  { id: "tf60", category: "POP CULTURE", statement: "Beyoncé was a founding member of Destiny's Child.", isTrue: true },

  // --- COMPUTER SCIENCE & TECH (61-75) ---
  { id: "tf61", category: "TECHNOLOGY", statement: "RAM stands for Read Access Memory.", isTrue: false },
  { id: "tf62", category: "TECHNOLOGY", statement: "Python is an interpreted programming language.", isTrue: true },
  { id: "tf63", category: "TECHNOLOGY", statement: "The first computer virus was created in 2001.", isTrue: false },
  { id: "tf64", category: "TECHNOLOGY", statement: "Binary code consists entirely of 0s and 1s.", isTrue: true },
  { id: "tf65", category: "TECHNOLOGY", statement: "Apple Inc. was co-founded by Steve Jobs and Steve Wozniak.", isTrue: true },
  { id: "tf66", category: "TECHNOLOGY", statement: "HTML is a programming language.", isTrue: false },
  { id: "tf67", category: "TECHNOLOGY", statement: "Linux is an open-source operating system kernel.", isTrue: true },
  { id: "tf68", category: "TECHNOLOGY", statement: "GPU stands for Graphics Processing Unit.", isTrue: true },
  { id: "tf69", category: "TECHNOLOGY", statement: "Ethernet ports use RJ-11 connectors.", isTrue: false },
  { id: "tf70", category: "TECHNOLOGY", statement: "Java and JavaScript are the same language.", isTrue: false },
  { id: "tf71", category: "TECHNOLOGY", statement: "The World Wide Web was invented by Tim Berners-Lee.", isTrue: true },
  { id: "tf72", category: "TECHNOLOGY", statement: "IPv4 addresses are 64 bits long.", isTrue: false },
  { id: "tf73", category: "TECHNOLOGY", statement: "SSD stands for Solid State Drive.", isTrue: true },
  { id: "tf74", category: "TECHNOLOGY", statement: "Bluetooth technology is named after a Nordic king.", isTrue: true },
  { id: "tf75", category: "TECHNOLOGY", statement: "Bitcoins can be physically minted as legal tender.", isTrue: false },

  // --- LITERATURE & ARTS (76-90) ---
  { id: "tf76", category: "LITERATURE", statement: "Shakespeare wrote 154 sonnets.", isTrue: true },
  { id: "tf77", category: "LITERATURE", statement: "'1984' was published in the year 1984.", isTrue: false },
  { id: "tf78", category: "LITERATURE", statement: "Agatha Christie wrote the Hercule Poirot mysteries.", isTrue: true },
  { id: "tf79", category: "LITERATURE", statement: "The Odyssey is longer than the Iliad.", isTrue: false },
  { id: "tf80", category: "LITERATURE", statement: "Don Quixote is regarded as the first modern novel.", isTrue: true },
  { id: "tf81", category: "LITERATURE", statement: "Mark Twain's real name was Samuel Langhorne Clemens.", isTrue: true },
  { id: "tf82", category: "LITERATURE", statement: "Edgar Allan Poe wrote 'The Raven'.", isTrue: true },
  { id: "tf83", category: "LITERATURE", statement: "The hobbit Bilbo Baggins lives in Rivendell.", isTrue: false },
  { id: "tf84", category: "LITERATURE", statement: "Dracula is vulnerable to silver bullets.", isTrue: false },
  { id: "tf85", category: "LITERATURE", statement: "Jane Eyre was written by Charlotte Brontë.", isTrue: true },
  { id: "tf86", category: "LITERATURE", statement: "Vincent van Gogh sold only one painting during his lifetime.", isTrue: true },
  { id: "tf87", category: "LITERATURE", statement: "The Louvre museum is located in London.", isTrue: false },
  { id: "tf88", category: "LITERATURE", statement: "The Statue of David was sculpted by Michelangelo.", isTrue: true },
  { id: "tf89", category: "LITERATURE", statement: "The Starry Night was painted by Claude Monet.", isTrue: false },
  { id: "tf90", category: "LITERATURE", statement: "Beethoven composed his Ninth Symphony while completely deaf.", isTrue: true },

  // --- MATHEMATICS & LOGIC (91-105) ---
  { id: "tf91", category: "MATHEMATICS", statement: "A prime number has exactly two positive divisors.", isTrue: true },
  { id: "tf92", category: "MATHEMATICS", statement: "The square root of 81 is 9.", isTrue: true },
  { id: "tf93", category: "MATHEMATICS", statement: "Zero is a positive integer.", isTrue: false },
  { id: "tf94", category: "MATHEMATICS", statement: "The sum of interior angles in a triangle is 180 degrees.", isTrue: true },
  { id: "tf95", category: "MATHEMATICS", statement: "Pi is a rational number.", isTrue: false },
  { id: "tf96", category: "MATHEMATICS", statement: "A heptagon has seven sides.", isTrue: true },
  { id: "tf97", category: "MATHEMATICS", statement: "2 to the power of 10 is equal to 1024.", isTrue: true },
  { id: "tf98", category: "MATHEMATICS", statement: "An acute angle is greater than 90 degrees.", isTrue: false },
  { id: "tf99", category: "MATHEMATICS", statement: "The Fibonacci sequence starts with 0 and 1.", isTrue: true },
  { id: "tf100", category: "MATHEMATICS", statement: "Parallel lines intersect at right angles.", isTrue: false },
  { id: "tf101", category: "MATHEMATICS", statement: "Every even number greater than 2 is the sum of two primes (Goldbach Conjecture).", isTrue: true },
  { id: "tf102", category: "MATHEMATICS", statement: "A circle has an infinite number of lines of symmetry.", isTrue: true },
  { id: "tf103", category: "MATHEMATICS", statement: "100 divided by 0.5 equals 50.", isTrue: false },
  { id: "tf104", category: "MATHEMATICS", statement: "The hypotenuse is the longest side of a right-angled triangle.", isTrue: true },
  { id: "tf105", category: "MATHEMATICS", statement: "The derivative of a constant function is 1.", isTrue: false },
];
